#E-Learning through video link is a web development approach which focuses on online learning through website by providing live learning interaction through video session between teacher and student
#It will also bring ease at global level to seek knowledge at this web platform where people can learn any topic from the teacher anywhere from the world of subjected domain without attending the physical class
#This system will deduct its commission from payment made bstudent to teacher and get its profit to run the business.
#Many data mining techniques are used to make complete analysis performed by using predictive analytics techniques to analyze the records to discover the trends.
#Data regarding the E-learning is collected from stakeholders by considering radomly data of (2002-2017)years to evaluate the predictions on the yearly profit of the managment
##X=(number of students(passed the courses), Y=yearly profit(%)and the students who successfully passes out and do tremendous work in information communication technology(ICT).later,these predictions will facilitate the E-learning monetarily while making beneficial effect or not.
X=c(250,260,600,400,160,200)
Y=c(60,70,75,63,82,70)
#for sigma X.........
sumx=sum(X)
#for sigma Y.......
sumy=sum(Y)
#for X_bar.........
x_bar=sum(X)/length(X)
#for Y_bar.........
Y_bar=sum(Y)/length(Y)
#for X(i)-X bar.......
new_list_X=X-x_bar
#for Y(i)-y bar.......
new_list_Y=Y-Y_bar
#for (X(i)-X bar)*(Y(i)-Y bar)......
new_list_XY=new_list_X*new_list_Y
#for sigma(X(i)-X_bar)(Y(i)-Y_bar)..........
Sumnew_list_XY=sum(new_list_XY)
#for (X(i)-X_bar)^2.........
new_list_XX=new_list_X*new_list_X
#for sigma(X(i)-X_bar)^2..........
Sumnew_list_XX=sum(new_list_XX)
#for the value of B1^=sigma(X(i)-X_bar)(Y(i)-Y_bar)/sigma(X(i)-X_bar)^2...........
B1_hat=Sumnew_list_XY/Sumnew_list_XX
#for the value of B0^=Y_bar-B1^*X_bar...........
B0_hat=Y_bar-B1_hat*x_bar
#for (Y(i)-Y_bar)^2.........
new_list_YY=new_list_Y*new_list_Y
#for sigma(Y(i)-Y_bar)^2..........
Sumnew_list_YY=sum(new_list_YY)
#for (Y(i)^-Y_bar)^2...........
#so the 1st step is to calculate B1^*X.....
B1_hat_X=B1_hat*X
#2ndly calculate Y^=B0^+B1^*X......
Y_hat=B0_hat+B1_hat_X
#3rdly calculate Y(i)^-Y_bar.....................
new_list_Yi_hat=Y_hat-Y_bar
#then finally for (Y(i)^-Y_bar)^2........
new_list_YY_hat=new_list_Yi_hat*new_list_Yi_hat
#for sigma (Y(i)^-Y_bar)^2..............
sumnew_list_YY_hat=sum(new_list_YY_hat)
#This is the 2nd assignment (Example3) in SLR done in R.Thankyou :)