#E-Learning through video link is a web development approach which focuses on online learning through website by providing live learning interaction through video session between teacher and student
#It will also bring ease at global level to seek knowledge at this web platform where people can learn any topic from the teacher anywhere from the world of subjected domain without attending the physical class
#This system will deduct its commission from payment made bstudent to teacher and get its profit to run the business.
#Many data mining techniques are used to make complete analysis performed by using predictive analytics techniques to analyze the records to discover the trends.
#Data regarding the E-learning is collected from stakeholders by considering radomly data of (2002-2017)years to evaluate the predictions on the yearly profit of the managment
#and the students who successfully passes out and do tremendous work in information communication technology(ICT).later,these predictions will facilitate the E-learning monetarily while making beneficial effect or not.
#X1=(number of students(passed the courses) , X2=number of teachers , Y=yearly profit(%)
           
X1=c(250,260,600,400,160,200)
X2=c(5,6,4,6,7,10)
Y=c(60,70,75,63,82,70)
#for sigma X1.........
sumX1=sum(X1)
#for sigma X2.......
sumX2=sum(X2)
#for sigma Y.......
sumY=sum(Y)
#for X1_bar.........
X1_bar=sum(X1)/length(X1)
#for X2_bar.........
X2_bar=sum(X2)/length(X2)
#for Y_bar.........
Y_bar=sum(Y)/length(Y)
#for X1_bar^2.........
X1_bar2=X1_bar*X1_bar
#for X2_bar^2.........
X2_bar2=X2_bar*X2_bar
#for x1=X1-X1_bar......
x1=X1-X1_bar
#for x2=X2-X2_bar......
x2=X2-X2_bar
#for y=Y-Y_bar......
y=Y-Y_bar
#formula1.........................................
#for B1^=(sigmax1.y.sigmax2^2)-(sigmax2.y.sigmax1.x2)/(sigmax1^2.sigmax2^2)-(sigma(x1x2))^2 .........
#for x1.y...........
x1y=x1*y
#for sigmax1.y.......
Sumx1y=sum(x1y)
#for (x2)^2.........
xx2=x2*x2
#for sigmax2^2..........
Sumxx2=sum(xx2)
#for the value of (sigmax1.y.sigmax2^2)
pt1=Sumx1y*Sumxx2
#for the value of (sigmax2.y.sigmax1.x2)
#for sigmax2.y.........
x2y=x2*y
Sumx2y=sum(x2y)
#for sigma(x1)(x2).........
x1x2=x1*x2
Sumx1x2=sum(x1x2)
#for the value of (sigmax2.y.sigmax1.x2)
pt2=Sumx2y*Sumx1x2
#calculate value of (sigmax1.y.sigmax2^2)-(sigmax2.y.sigmax1.x2)........
part1=pt1-pt2
#for value of (sigmax1^2.sigmax2^2)-(sigma(x1x2))^2............
# for the value of (sigmax1^2.sigmax2^2)..........
#for (x1)^2.........
xx1=x1*x1
#for sigma(x1)^2.........
Sumxx1=sum(xx1)
#sigma(x2)^2 is(solved above is)
pt3=Sumxx1*Sumxx2
#for the value of (sigma(x1x2))^2...............
pt4=Sumx1x2*Sumx1x2
#calculate value of (sigmax1^2.sigmax2^2)-(sigma(X1X2))^2"........
part2=pt3-pt4
#for B1^............
B1_hat=part1/part2
#.............formula2.........................................

#for B2^=(sigmax2.y.sigmax1^2)-(sigmax1.y.sigmax1.x2)/(sigmax1^2.sigmax2^2)-(sigma(x1x2))^2.........
#firstly calculate (sigmax2.y.sigmax1^2.........
ptt1=Sumx2y*Sumxx1
#2ndly calculate (sigmax1.y.sigmax1.x2)........
ptt2=Sumx1y*Sumx1x2
#calculate value of (sigmax2.y.sigmax1^2)-(sigmax1.y.sigmax1.x2)........
partt1=ptt1-ptt2
#for B2^............
#part2 is caculated above..........
B2_hat=partt1/part2

#formula3.........................................
#for B0^=(Y_bar)-(B1^.X1_bar)-(B2^.X2_bar)..........
B0_hat=Y_bar-B1_hat*X1_bar-B2_hat*X2_bar

#formula4...........................................
#for Y^=B1^*X1+B2^*X2..............
#so the 1st step is to calculate B1^*X1
B1_hatX1=B1_hat*X1
#so the 2nd step is to calculate B2^*X2
B2_hatX2=B2_hat*X2
Y_hat=B0_hat+B1_hatX1+B2_hatX2

#formula5...........................................
#for TSS=sigma(Y-Y_bar)^2............
#calculate value of (Y-Y_bar)^2
y2=y*y
TSS=sum(y2)

#formula6............................................
#for MSS=sigma(Y^-Y_bar)^2...............
#for (Y^-Y_bar)........
Value_listYi_hat=Y_hat-Y_bar
#for (Y^-Y_bar)^2........
Yi_hat=Value_listYi_hat*Value_listYi_hat
#for sigma (Y(i)^-Y_bar)^2.............
MSS=sum(Yi_hat)

#formula7..............................
#for RSS=sigma(Y-Y^)^2...........
#1stly calculate value of (Y-Y^)
YY_hat=Y-Y_hat
#then finally for (Y-Y^)^2........
Yi_hat2=YY_hat*YY_hat
#for sigma (Y-Y^)^2.............
RSS=sum(Yi_hat2)
#formula8.............................

#for <^2=RSS/n-k .............
#k=no. of parameters=3 i.e(B1,B2,B0) and n=7......
k=3
n=7
nk=n-k         
sigma_hat2=RSS/nk

#...................formula9.............................

#for V(B1^)=<^2. sigmax2^2)/ (sigmax1^2.sigmax2^2)-(sigma(x1x2))^2"
vB1_hat=sigma_hat2*(Sumxx2/part2)

#....................formula10............................

#for V(B2^)=<^2. sigmax1^2)/ (sigmax1^2.sigmax2^2)-(sigma(x1x2))^2...................
vB2_hat=sigma_hat2*(Sumxx1/part2)
#......................formula11............................

#for V(B0^)=<^2. 1/n+[X1_bar^2.sigmax2^2+X2_bar^2.sigmax1^2+2X1_bar.X2_bar.sigmax1x2]/ (sigmax1^2.sigmax2^2)-(sigma(x1x2))^2...................
#for [X1_bar^2.sigmax2^2+X2_bar^2.sigmax1^2+2X1_bar.X2_bar.sigmax1x2]
#1stly calculate X1_bar^2.sigmax2^2
vpt1=X1_bar2*Sumxx2
#2ndly calculate X2_bar^2.sigmax1^2
vpt2=X2_bar2*Sumxx1
#3rdly calculate 2X1_bar.X2_bar.sigmax1x2
vpt3=2*X1_bar*X2_bar*Sumx1x2
#so value of [X1_bar^2.sigmax2^2+X2_bar^2.sigmax1^2+2X1_bar.X2_bar.sigmax1x2] 
vB0part1=vpt1+vpt2+vpt3
vb1=1/n
vb2=vB0part1/part2
vb0=vb1+vb2
VB0_hat=sigma_hat2*vb0
#This is the 2nd Assignment(example.3)of Stat701 in R.Thanku for watching :)
